name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Build Patches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v3

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew :patches:buildAndroid

      - name: Upload patch jar
        uses: actions/upload-artifact@v4
        with:
          name: revanced-patches
          path: "**/build/libs/*.jar"
